platform :ios, ‘7.0’

target 'PintiJewelry’ do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'Reachability', '~> 3.2'
   pod 'RESideMenu', '~> 4.0.7'
   pod 'Masonry', '~> 1.0.1’
   pod 'SDWebImage', '~> 3.8.1'
   pod 'PopMenu'
end